"""add matches.forfeit

Revision ID: 044709eb77fb
Revises: 9fc63cc084fc
Create Date: 2026-08-13 00:28:15.664060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044709eb77fb'
down_revision: Union[str, None] = '9fc63cc084fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('forfeit', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'forfeit')
    # ### end Alembic commands ###
