"""add event category column

Revision ID: 1d3507045e17
Revises: 044709eb77fb
Create Date: 2026-08-13 01:29:17.275532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3507045e17'
down_revision: Union[str, None] = '044709eb77fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
