"""add user profiles

Revision ID: 7896ba44cd2d
Revises: 1d3507045e17
Create Date: 2026-08-14 16:05:55.509551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7896ba44cd2d'
down_revision: Union[str, None] = '1d3507045e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('custom_rosters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_custom_rosters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_rosters'))
    )
    op.create_index(op.f('ix_custom_rosters_user_id'), 'custom_rosters', ['user_id'], unique=False)
    op.create_table('favorite_teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_favorite_teams_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_teams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_teams')),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_favorite_teams_user_team')
    )
    op.create_index(op.f('ix_favorite_teams_team_id'), 'favorite_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_favorite_teams_user_id'), 'favorite_teams', ['user_id'], unique=False)
    op.create_table('custom_roster_players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('roster_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_custom_roster_players_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roster_id'], ['custom_rosters.id'], name=op.f('fk_custom_roster_players_roster_id_custom_rosters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_roster_players')),
    sa.UniqueConstraint('roster_id', 'player_id', name='uq_custom_roster_players_roster_player')
    )
    op.create_index(op.f('ix_custom_roster_players_player_id'), 'custom_roster_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_custom_roster_players_roster_id'), 'custom_roster_players', ['roster_id'], unique=False)
    op.create_table('saved_matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_saved_matches_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_matches')),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_saved_matches_user_match')
    )
    op.create_index(op.f('ix_saved_matches_match_id'), 'saved_matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_saved_matches_user_id'), 'saved_matches', ['user_id'], unique=False)
    op.create_table('saved_predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=True),
    sa.Column('team_a_id', sa.BigInteger(), nullable=True),
    sa.Column('team_b_id', sa.BigInteger(), nullable=True),
    sa.Column('team_a_name', sa.String(length=255), nullable=False),
    sa.Column('team_b_name', sa.String(length=255), nullable=False),
    sa.Column('prob_a', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('prob_b', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('predicted_winner', sa.String(length=255), nullable=False),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_saved_predictions_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], name=op.f('fk_saved_predictions_team_a_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], name=op.f('fk_saved_predictions_team_b_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_predictions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_predictions'))
    )
    op.create_index(op.f('ix_saved_predictions_match_id'), 'saved_predictions', ['match_id'], unique=False)
    op.create_index(op.f('ix_saved_predictions_user_id'), 'saved_predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_predictions_user_id'), table_name='saved_predictions')
    op.drop_index(op.f('ix_saved_predictions_match_id'), table_name='saved_predictions')
    op.drop_table('saved_predictions')
    op.drop_index(op.f('ix_saved_matches_user_id'), table_name='saved_matches')
    op.drop_index(op.f('ix_saved_matches_match_id'), table_name='saved_matches')
    op.drop_table('saved_matches')
    op.drop_index(op.f('ix_custom_roster_players_roster_id'), table_name='custom_roster_players')
    op.drop_index(op.f('ix_custom_roster_players_player_id'), table_name='custom_roster_players')
    op.drop_table('custom_roster_players')
    op.drop_index(op.f('ix_favorite_teams_user_id'), table_name='favorite_teams')
    op.drop_index(op.f('ix_favorite_teams_team_id'), table_name='favorite_teams')
    op.drop_table('favorite_teams')
    op.drop_index(op.f('ix_custom_rosters_user_id'), table_name='custom_rosters')
    op.drop_table('custom_rosters')
    op.drop_table('users')
    # ### end Alembic commands ###
