"""initial schema

Revision ID: 9fc63cc084fc
Revises: 
Create Date: 2026-08-13 00:08:13.198895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc63cc084fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('prize_pool', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pandascore_id', sa.BigInteger(), nullable=True),
    sa.Column('vlr_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('pandascore_id', name=op.f('uq_events_pandascore_id')),
    sa.UniqueConstraint('vlr_id', name=op.f('uq_events_vlr_id'))
    )
    op.create_index(op.f('ix_events_region'), 'events', ['region'], unique=False)
    op.create_index(op.f('ix_events_tier'), 'events', ['tier'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rows_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('acronym', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('current_rating', sa.Numeric(precision=8, scale=2), server_default='1500', nullable=False),
    sa.Column('pandascore_id', sa.BigInteger(), nullable=True),
    sa.Column('vlr_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('pandascore_id', name=op.f('uq_teams_pandascore_id')),
    sa.UniqueConstraint('vlr_id', name=op.f('uq_teams_vlr_id'))
    )
    op.create_index(op.f('ix_teams_normalized_name'), 'teams', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_teams_region'), 'teams', ['region'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('team_a_id', sa.BigInteger(), nullable=True),
    sa.Column('team_b_id', sa.BigInteger(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('pandascore_id', sa.BigInteger(), nullable=True),
    sa.Column('vlr_id', sa.String(length=32), nullable=True),
    sa.Column('enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_matches_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], name=op.f('fk_matches_team_a_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], name=op.f('fk_matches_team_b_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], name=op.f('fk_matches_winner_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('pandascore_id', name=op.f('uq_matches_pandascore_id')),
    sa.UniqueConstraint('vlr_id', name=op.f('uq_matches_vlr_id'))
    )
    op.create_index(op.f('ix_matches_event_id'), 'matches', ['event_id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_team_a_id'), 'matches', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_matches_team_b_id'), 'matches', ['team_b_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('pandascore_id', sa.BigInteger(), nullable=True),
    sa.Column('vlr_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('pandascore_id', name=op.f('uq_players_pandascore_id')),
    sa.UniqueConstraint('vlr_id', name=op.f('uq_players_vlr_id'))
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('rankings_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_rankings_snapshots_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rankings_snapshots')),
    sa.UniqueConstraint('team_id', 'snapshot_date', name='uq_rankings_snapshots_team_date')
    )
    op.create_index(op.f('ix_rankings_snapshots_region'), 'rankings_snapshots', ['region'], unique=False)
    op.create_index(op.f('ix_rankings_snapshots_snapshot_date'), 'rankings_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_rankings_snapshots_team_id'), 'rankings_snapshots', ['team_id'], unique=False)
    op.create_table('match_maps',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=True),
    sa.Column('map_order', sa.Integer(), nullable=True),
    sa.Column('picked_by', sa.String(length=255), nullable=True),
    sa.Column('team_a_score', sa.Integer(), nullable=True),
    sa.Column('team_b_score', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_maps_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], name=op.f('fk_match_maps_winner_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_maps')),
    sa.UniqueConstraint('match_id', 'map_order', name='uq_match_maps_match_order')
    )
    op.create_index(op.f('ix_match_maps_match_id'), 'match_maps', ['match_id'], unique=False)
    op.create_table('match_player_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('match_map_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('acs', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rating', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('adr', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_map_id'], ['match_maps.id'], name=op.f('fk_match_player_stats_match_map_id_match_maps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_player_stats_player_id_players'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_player_stats_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_player_stats'))
    )
    op.create_index(op.f('ix_match_player_stats_match_map_id'), 'match_player_stats', ['match_map_id'], unique=False)
    op.create_index(op.f('ix_match_player_stats_player_id'), 'match_player_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_player_stats_player_id'), table_name='match_player_stats')
    op.drop_index(op.f('ix_match_player_stats_match_map_id'), table_name='match_player_stats')
    op.drop_table('match_player_stats')
    op.drop_index(op.f('ix_match_maps_match_id'), table_name='match_maps')
    op.drop_table('match_maps')
    op.drop_index(op.f('ix_rankings_snapshots_team_id'), table_name='rankings_snapshots')
    op.drop_index(op.f('ix_rankings_snapshots_snapshot_date'), table_name='rankings_snapshots')
    op.drop_index(op.f('ix_rankings_snapshots_region'), table_name='rankings_snapshots')
    op.drop_table('rankings_snapshots')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_team_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_a_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_event_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_region'), table_name='teams')
    op.drop_index(op.f('ix_teams_normalized_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_events_tier'), table_name='events')
    op.drop_index(op.f('ix_events_region'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
